"""HMS Resolution — Method 3 round-2 research tests.

M7 (HMS Ambush) returned NO-GO. Two concerns from the admiral's review:

1. The Round-1 surface BC was the *discrete in-dough sensor* time series
   (e.g. T6 for BA3C). That sensor is itself in-dough and plateaus near
   100 °C, so the BC was a fake-plateau and the inverse problem became
   information-free over most of the bake.
2. |ρ(α, x_core)| ≈ 0.9 across five heterogeneous bakes is suspiciously
   uniform — could indicate optimiser laziness rather than structural
   degeneracy.

This file retests with three fixes:

* :class:`TestRealCSVViabilityV2` — same 7 real fixtures, but the BC is
  built from a per-timestep linear *spatial* interpolation of all 8
  sensors at the M2a continuous interface position
  ``surface_assignment.position_normalised``.
* :class:`TestProfileLikelihood` — refit α only at each x_core in a
  25-point grid on 3 representative fixtures. Distinguishes structural
  degeneracy (loss flat) from optimiser laziness (loss has a basin).
* :class:`TestSyntheticShallowInsertionMisfit` — model-misfit baseline
  on a synthetic that was NOT generated by the heat-eq forward solver.
  Tests whether the heat-equation model class fits this geometry at all,
  not just self-consistent synthetic data.

Memory-feedback compliance:

* TDD — sanity test on synthetic recovery (v2 result on a synthetic
  whose true BC IS the interpolation) is the gating test; if it fails
  the rest is moot.
* DRY — reuses ``interpolate_temperature_series_at`` from
  ``profile.py``; reuses the v1 ``_segmented_real_fixture`` and helpers
  from ``test_heat_equation_research``.
"""

from __future__ import annotations

import math
import os
import sys
from typing import Optional

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.data.spatial_reconstruction.classifier import classify  # noqa: E402
from src.data.spatial_reconstruction.geometry import lookup_geometry  # noqa: E402
from src.data.spatial_reconstruction.heat_equation import (  # noqa: E402
    fit_heat_equation_inverse_v2,
    profile_likelihood_x_core,
    solve_heat_eq_forward,
)
from tests.fixtures.curve_boundary_cases import CASES  # noqa: E402
from tests.test_heat_equation_research import (  # noqa: E402
    REAL_FIXTURES,
    SENSOR_NAMES,
    SENSOR_POSITIONS,
    _segmented_real_fixture,
    _synthetic_dough_observations,
)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


_M6_SURFACE_POSITION_CACHE: dict[tuple, float] = {}


def _classifier_x_surface_for_spec(spec: dict) -> float:
    """Return the M2a-inferred continuous x_dough_air for a fixture spec.

    Cached per (fixture_name, expected_curve_idx) to avoid re-running the
    classifier on every test.
    """
    key = (spec["fixture_name"], spec["expected_curve_idx"])
    if key in _M6_SURFACE_POSITION_CACHE:
        return _M6_SURFACE_POSITION_CACHE[key]
    df = _segmented_real_fixture(spec)
    geom = lookup_geometry(probe_sn=None, probe_model=None)
    a = classify(df, sample_period_ms=5000, probe_geometry=geom)
    if a.surface_assignment is None:
        # Full-immersion: no interface. Fall back to the v1 spec's discrete
        # x_surface so the test still has something to invert.
        x = float(spec["x_surface"])
    else:
        x = float(a.surface_assignment.position_normalised)
    _M6_SURFACE_POSITION_CACHE[key] = x
    return x


# ---------------------------------------------------------------------------
# Class 1 — Sanity check: v2 on a synthetic whose true BC IS the interp.
# ---------------------------------------------------------------------------


class TestV2SanityOnSynthetic:
    """v2 should reproduce v1's synthetic-recovery numbers when the
    interface lies on a sensor (so the 'interpolated' BC reduces to the
    sensor's own time series and the two methods agree).
    """

    def test_recovers_known_x_core_no_noise_v2(self):
        x_core_true = -0.15
        alpha_true = 1.5e-3
        df, surf = _synthetic_dough_observations(
            alpha_true=alpha_true,
            x_core_true=x_core_true,
            x_surface=5 / 7,  # T6 position
            in_dough_sensors=("T1", "T2", "T3", "T4", "T5"),
            noise_sigma_c=0.0,
            seed=1,
        )
        # Overwrite T6 with the surface BC so the interpolation at x = 5/7
        # reduces exactly to surf — establishes that v2 wiring is sane on a
        # case where its BC equals the v1 BC.
        df["T6"] = surf
        df["T7"] = surf
        df["T8"] = surf
        result = fit_heat_equation_inverse_v2(
            df=df,
            in_dough_sensors=["T1", "T2", "T3", "T4", "T5"],
            x_surface_continuous=5 / 7,
            x_core_init=-0.05,
            alpha_init=1e-3,
            downsample_factor=4,
        )
        assert result["converged"], f"v2 did not converge: {result}"
        assert result["bc_source"] == "interpolated_v2"
        # Same recovery quality as v1's synthetic test.
        assert abs(result["x_core"] - x_core_true) < 0.02, (
            f"x_core_fit = {result['x_core']:.4f}; expected ≈ {x_core_true}"
        )
        assert abs(result["alpha"] - alpha_true) / alpha_true < 0.5, (
            f"alpha_fit = {result['alpha']:.2e}; expected ≈ {alpha_true:.2e}"
        )


# ---------------------------------------------------------------------------
# Class 2 — Real-CSV viability with corrected BC
# ---------------------------------------------------------------------------


class TestRealCSVViabilityV2:
    """Re-run the M7 viability sweep with the corrected BC.

    Parametrised over the same 7 real fixtures as M7. For each, derive
    ``x_surface_continuous`` from the M2a classifier's
    ``surface_assignment.position_normalised`` (the M6 inferred position),
    then call :func:`fit_heat_equation_inverse_v2`.
    """

    _RESULTS: dict[str, dict] = {}

    @pytest.mark.parametrize(
        "spec",
        REAL_FIXTURES,
        ids=lambda s: s["label"],
    )
    def test_v2_inversion_runs_on_real_csv(self, spec):
        df = _segmented_real_fixture(spec)
        x_surf_cont = _classifier_x_surface_for_spec(spec)
        result = fit_heat_equation_inverse_v2(
            df=df,
            in_dough_sensors=spec["in_dough"],
            x_surface_continuous=x_surf_cont,
            x_core_init=-0.05,
            alpha_init=1e-3,
            downsample_factor=4,
        )
        TestRealCSVViabilityV2._RESULTS[spec["label"]] = {
            **result,
            "fixture_name": spec["fixture_name"],
            "expected_curve_idx": spec["expected_curve_idx"],
            "n_in_dough": len(spec["in_dough"]),
            "x_surface_continuous": x_surf_cont,
            "in_dough": list(spec["in_dough"]),
        }
        # Hard contract: optimiser must run.
        assert result["converged"] or result["n_iter"] >= 50, (
            f"{spec['label']}: optimiser failed to make progress"
            f" (iter={result['n_iter']})"
        )


# ---------------------------------------------------------------------------
# Class 3 — Profile-likelihood diagnostic
# ---------------------------------------------------------------------------


# The 3 representative fixtures for the profile-likelihood scan: a
# motivating BA3C, a different probe (100098DE picks T7 as surface), and a
# lidded case that was pathological in M7.
PROFILE_LIKELIHOOD_LABELS = ("BA3C_0946", "100098DE_1351", "wonder_white")
PROFILE_LIKELIHOOD_FIXTURES = [
    s for s in REAL_FIXTURES if s["label"] in PROFILE_LIKELIHOOD_LABELS
]


class TestProfileLikelihood:
    """Profile-likelihood scan on 3 representative fixtures.

    Grid: x_core ∈ [-0.5, +0.5] in 25 steps. For each fixture, refit α
    only and record the (x_core, alpha_best, loss) curve.

    Verdict criterion (computed at report time, not asserted here):

    * Loss-flat fraction = (max(loss) - min(loss)) / median(loss) over the
      grid. If it is < 0.05, the loss is genuinely flat (structural
      degeneracy). If it is large with a clear minimum interior to the
      grid, the M7 joint optimiser converged early.
    """

    _RESULTS: dict[str, pd.DataFrame] = {}

    @pytest.mark.parametrize(
        "spec",
        PROFILE_LIKELIHOOD_FIXTURES,
        ids=lambda s: s["label"],
    )
    def test_profile_likelihood_scan(self, spec):
        df = _segmented_real_fixture(spec)
        x_surf_cont = _classifier_x_surface_for_spec(spec)
        # Grid stays interior to x_surface_continuous (the model rejects
        # x_core ≥ x_surface). Truncate to safe range.
        upper = min(0.5, x_surf_cont - 0.05)
        x_grid = np.linspace(-0.5, upper, 25)
        scan = profile_likelihood_x_core(
            df=df,
            in_dough_sensors=spec["in_dough"],
            x_surface_continuous=x_surf_cont,
            x_core_grid=x_grid,
            alpha_init=1e-3,
            downsample_factor=4,
        )
        TestProfileLikelihood._RESULTS[spec["label"]] = scan
        # Soft contract: at least 80% of grid points must yield a finite loss.
        finite_count = int(np.isfinite(scan["loss"]).sum())
        assert finite_count >= int(0.8 * len(x_grid)), (
            f"{spec['label']}: only {finite_count}/{len(x_grid)} grid "
            f"points produced a finite loss"
        )


# ---------------------------------------------------------------------------
# Class 4 — synthetic_shallow_insertion misfit baseline
# ---------------------------------------------------------------------------


class TestSyntheticShallowInsertionMisfit:
    """True model-misfit baseline.

    ``synthetic_shallow_insertion`` was generated by the role-classifier
    fixture-builder, NOT by the heat-eq forward solver. Inverting it tests
    whether the heat equation is the right *model class* for this
    geometry, not just for self-consistent synthetic data.
    """

    _RESULTS: dict = {}

    def test_synthetic_shallow_insertion_misfit(self):
        case = next(
            c for c in CASES if c["name"] == "synthetic_shallow_insertion"
        )
        df = case["df"].copy()
        # Restrict to the bake window (matches the fixture annotations).
        starts = case.get("expected_starts") or [0]
        ends = case.get("expected_ends") or [len(df) - 1]
        s, e = int(starts[0]), int(ends[0])
        sub = df.iloc[s : e + 1].reset_index(drop=True)
        if "Timestamp" in sub.columns:
            t0 = float(sub["Timestamp"].iloc[0])
            sub["Timestamp"] = sub["Timestamp"].to_numpy(dtype=float) - t0
        # Fixture's ground-truth interface is at 2.5/7 ≈ 0.357.
        x_surf_cont = float(case["expected_x_dough_air_normalised"])
        # In-dough = T1, T2 (the fixture's ground-truth dough sensors).
        in_dough = ["T1", "T2"]
        result = fit_heat_equation_inverse_v2(
            df=sub,
            in_dough_sensors=in_dough,
            x_surface_continuous=x_surf_cont,
            x_core_init=-0.05,
            alpha_init=1e-3,
            downsample_factor=2,
        )

        # Per-sensor RMSE breakdown (informative — not asserted hard).
        from src.data.spatial_reconstruction.heat_equation import (
            _build_observation_matrix,
            solve_heat_eq_forward as fwd,
        )
        from src.data.spatial_reconstruction.profile import (
            interpolate_temperature_series_at,
        )

        t_obs, T_obs, x_obs = _build_observation_matrix(
            df=sub,
            in_dough_sensors=in_dough,
            sensor_names=SENSOR_NAMES,
            sensor_positions_normalised=SENSOR_POSITIONS,
            downsample_factor=2,
        )
        surf_full = interpolate_temperature_series_at(
            sub,
            positions=SENSOR_POSITIONS,
            x_target=x_surf_cont,
            sensors=SENSOR_NAMES,
        ).to_numpy(dtype=float)
        t_full = sub["Timestamp"].to_numpy(dtype=float)
        T_surf_obs = np.interp(t_obs, t_full, surf_full)
        T_pred = fwd(
            alpha=result["alpha"],
            x_core=result["x_core"],
            x_surface=x_surf_cont,
            t_grid=t_obs,
            T_surface_series=T_surf_obs,
            T_initial=result["T_initial"],
            n_spatial=30,
            sample_x=x_obs,
        )
        per_sensor_rmse = {
            in_dough[k]: float(np.sqrt(np.mean((T_pred[:, k] - T_obs[:, k]) ** 2)))
            for k in range(len(in_dough))
        }

        TestSyntheticShallowInsertionMisfit._RESULTS = {
            **result,
            "per_sensor_rmse": per_sensor_rmse,
            "x_surface_continuous": x_surf_cont,
            "in_dough": list(in_dough),
        }
        # Hard contract: classifier converges. The question is whether the
        # residuals are small, not whether the optimiser ran.
        assert result["converged"] or result["n_iter"] >= 30, (
            f"shallow insertion: optimiser failed (iter={result['n_iter']})"
        )
